# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' ConvexHullMD
#'
#' Uses Jarvis March algorithm to find the convex hull of a list of 2D vectors.
#'
#' @param LofV List of 2D vectors.
#' @return List of 2D vectors representing vertices of the convex hull.
ConvexHullMD <- function(LofV) {
    .Call(`_JarvisMarchMD_ConvexHullMD`, LofV)
}

