// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ConvexHullMD
std::list<std::vector<double>> ConvexHullMD(std::list<std::vector<double>> LofV);
RcppExport SEXP _JarvisMarchMD_ConvexHullMD(SEXP LofVSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::list<std::vector<double>> >::type LofV(LofVSEXP);
    rcpp_result_gen = Rcpp::wrap(ConvexHullMD(LofV));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_JarvisMarchMD_ConvexHullMD", (DL_FUNC) &_JarvisMarchMD_ConvexHullMD, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_JarvisMarchMD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
